baseURL = "https://riceset.com/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "articles"

  # "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  rssFullText = true

[languages]
  [languages.en]
    title = "riceset"
    subtitle = ""
    keywords = ""
    # copyright = ""
    copyright = "© 2022 riceset"
    menuMore = "Show more"
    writtenBy = "Written by "
    readMore = "Read more"
    readOtherPosts = "Suggested"
    newerPosts = "Newer articles"
    olderPosts = "Older articles"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
    logoText = "riceset"
    # logoHomeLink = "/"
    # path = "/riceset.svg"
    # alt = "riceset"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/riceset"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/riceset"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/index.xml"
        weight = 3

# Tags
[taxonomies]
   tag = "tags"
   category = "categories"
